AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/*'
    - 'public/system/**/*'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'
    - 'Guardfile'
Metrics/LineLength:
  Max: 220
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/Documentation:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - 'db/schema.rb'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Metrics/MethodLength:
  Max: 12
