AllCops:
  Exclude:
    - 'bin/*'
    - 'public/system/**/*'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'
    - 'Guardfile'
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2
  ExtraDetails: true
  DisplayStyleGuide: true
  DisplayCopNames: true
Rails:
  Enabled: True
Metrics/LineLength:
  Max: 220
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/Documentation:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'db/schema.rb'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Metrics/MethodLength:
  Max: 12
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
